#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.8 -y
apt-get update
apt-get install haproxy=2.8.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 531641-web-01 100.25.134.238:80 check
        server 531641-web-02 3.86.7.168:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
