#!/bin/bash
#script to block all incoming traffic except ssh, http and https

sudo su
apt-get install ufw
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw status
sudo ufw reload

